### ISSUE TITLE
加入插件后提示NotImplementedError

### ISSUE THREAD

**Issue by Xchkoo** [MeetWq/nonebot-plugin-asoulcnki#3]
terminal显示：
```
05-07 01:18:56 [SUCCESS] nonebot | NoneBot is initializing...
05-07 01:18:56 [INFO] nonebot | Current Env: dev
05-07 01:18:56 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 24967, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'1524049410'}, 'nickname': {'vb', 'Valorant_bot'}, 'command_start': {'!', '/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'fastapi_reload': True, 'sqlite_host': './db.db3', 'server_status_only_superusers': 'False', 'environment': 'dev'}
05-07 01:18:57 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
05-07 01:18:59 [SUCCESS] nonebot | Succeeded to import "nonebot.plugins.echo"
05-07 01:19:07 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
05-07 01:19:08 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_navicat"
05-07 01:19:10 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_asoulcnki"
05-07 01:19:10 [SUCCESS] nonebot | Succeeded to import "su-test"
05-07 01:19:11 [SUCCESS] nonebot | Succeeded to import "kaihei"
05-07 01:19:11 [SUCCESS] nonebot | Succeeded to import "help"
05-07 01:19:11 [WARNING] uvicorn | The --reload flag should not be used in production on Windows.
05-07 01:19:11 [INFO] uvicorn | Started server process [23880]
05-07 01:19:11 [INFO] uvicorn | Waiting for application startup.
05-07 01:19:15 [INFO] nonebot_plugin_gocqhttp | Startup complete, Web UI has served to http://127.0.0.1:24967/go-cqhttp/
05-07 01:19:15 [INFO] nonebot_plugin_navicat | Connect to Sqlite
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<Connection.run() done, defined at C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_connection.py:191> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_connection.py", line 198, in run
    await self._transport.connect()
  File "C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_transport.py", line 140, in connect
    raise exc
  File "C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_transport.py", line 128, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1676, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
05-07 01:19:15 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\starlette\routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\starlette\routing.py", line 518, in __aenter__
    await self._router.startup()
  File "C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\starlette\routing.py", line 598, in startup
    await handler()
  File "C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nonebot_plugin_htmlrender\__init__.py", line 27, in init
    browser = await get_browser(**kwargs)
  File "C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nonebot_plugin_htmlrender\browser.py", line 40, in get_browser
    return _browser or await init(**kwargs)
  File "C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nonebot_plugin_htmlrender\browser.py", line 26, in init
    _playwright = await async_playwright().start()
  File "C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_connection.py", line 198, in run
    await self._transport.connect()
  File "C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_transport.py", line 140, in connect
    raise exc
  File "C:\Users\Xchkoo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_transport.py", line 128, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1676, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

05-07 01:19:15 [ERROR] uvicorn | Application startup failed. Exiting.
```
* 求助

**Comment by MeetWq** [comment]
需要把 `fastapi_reload` 设为 `False`
参考：https://v2.nonebot.dev/docs/tutorial/choose-driver#fastapi_reload

**Comment by Xchkoo** [comment]
谢谢巨巨！
